"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Mail, UserPlus } from "lucide-react";
import { toast } from "sonner";
import type { OrganisationPermission } from "@/types/accesscheck";

type Member = { id: string; email: string | null; display_name: string | null; job_title: string | null; status: "active" | "inactive"; last_active_at: string | null; organisation_member_permissions: Array<{ permission: OrganisationPermission }> };
type Invitation = { id: string; email: string; permissions: OrganisationPermission[]; status: string; expires_at: string; created_at: string };
const roles: Array<{ value: OrganisationPermission; label: string; description: string }> = [{ value: "author", label: "Author", description: "Create and edit cases" }, { value: "reviewer", label: "Reviewer", description: "Review and approve" }, { value: "admin", label: "Admin", description: "Manage organisation" }];

export default function MembersClient({ initialMembers, initialInvitations, canAdmin }: { initialMembers: Member[]; initialInvitations: Invitation[]; canAdmin: boolean }) {
  const router = useRouter(); const [email, setEmail] = useState(""); const [inviteRoles, setInviteRoles] = useState<OrganisationPermission[]>(["author"]); const pending = initialInvitations.filter((invite) => invite.status === "pending");
  const toggle = (values: OrganisationPermission[], value: OrganisationPermission) => values.includes(value) ? values.filter((item) => item !== value) : [...values, value];
  const updateMember = async (member: Member, permissions: OrganisationPermission[], status = member.status) => { const response = await fetch("/api/organisations/members", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ memberId: member.id, permissions, status }) }); const body = await response.json(); if (!response.ok) return toast.error(body.error); toast.success("Member updated"); router.refresh(); };
  const invite = async (targetEmail = email, permissions = inviteRoles) => { const response = await fetch("/api/organisations/invitations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: targetEmail, permissions }) }); const body = await response.json(); if (!response.ok) return toast.error(body.error); toast.success(targetEmail === email ? "Invitation sent" : "Invitation resent"); setEmail(""); router.refresh(); };
  const cancel = async (id: string) => { const response = await fetch("/api/organisations/invitations", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ invitationId: id, action: "cancel" }) }); const body = await response.json(); if (!response.ok) return toast.error(body.error); toast.success("Invitation cancelled"); router.refresh(); };
  return <div className="space-y-6">{canAdmin && <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Invite member</h2><p className="text-sm text-slate-500">New members receive baseline Viewer access plus selected roles.</p><div className="mt-4 grid gap-3 lg:grid-cols-[1fr_1.5fr_auto]"><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="name@council.gov.uk" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /><div className="flex flex-wrap gap-2">{roles.map((role) => <label key={role.value} className={`cursor-pointer rounded-xl border px-3 py-2 text-xs font-bold ${inviteRoles.includes(role.value) ? "border-primary bg-primary-light text-primary" : "border-slate-200"}`}><input type="checkbox" className="sr-only" checked={inviteRoles.includes(role.value)} onChange={() => setInviteRoles(toggle(inviteRoles, role.value))} />{role.label}</label>)}</div><button onClick={() => invite()} disabled={!email.trim()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40"><UserPlus size={17} /> Invite</button></div></section>}
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-bold">Organisation members</h2><p className="text-sm text-slate-500">Viewer access is included for every active member.</p></div><div className="divide-y divide-slate-100">{initialMembers.map((member) => <MemberRow key={member.id} member={member} canAdmin={canAdmin} onSave={updateMember} />)}</div></section>
    {pending.length > 0 && <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-bold">Pending invitations</h2></div><div className="divide-y divide-slate-100">{pending.map((invitation) => <div key={invitation.id} className="flex flex-wrap items-center gap-3 px-5 py-4"><Mail size={18} className="text-slate-400" /><div className="min-w-0 flex-1"><p className="truncate font-semibold">{invitation.email}</p><p className="text-xs text-slate-500">{invitation.permissions.join(", ") || "Viewer"} · expires {new Date(invitation.expires_at).toLocaleDateString("en-GB")}</p></div>{canAdmin && <><button onClick={() => invite(invitation.email, invitation.permissions)} className="text-xs font-bold text-primary">Resend</button><button onClick={() => cancel(invitation.id)} className="text-xs font-bold text-red-600">Cancel</button></>}</div>)}</div></section>}
  </div>;
}

function MemberRow({ member, canAdmin, onSave }: { member: Member; canAdmin: boolean; onSave: (member: Member, permissions: OrganisationPermission[], status?: "active" | "inactive") => void }) {
  const [permissions, setPermissions] = useState(member.organisation_member_permissions.map((role) => role.permission));
  return <div className="px-5 py-4"><div className="flex flex-wrap items-start gap-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary-light font-extrabold text-primary">{(member.display_name || member.email || "U")[0].toUpperCase()}</div><div className="min-w-0 flex-1"><p className="font-bold text-slate-900">{member.display_name || member.email || "Unnamed member"}</p><p className="text-xs text-slate-500">{member.email}{member.job_title ? ` · ${member.job_title}` : ""}</p></div><span className={`rounded-lg px-2.5 py-1 text-xs font-bold capitalize ${member.status === "active" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{member.status}</span></div><div className="mt-3 flex flex-wrap items-center gap-2 pl-14">{roles.map((role) => <label key={role.value} title={role.description} className={`rounded-lg border px-2.5 py-1.5 text-xs font-bold ${permissions.includes(role.value) ? "border-primary/30 bg-primary-light text-primary" : "border-slate-200 text-slate-500"}`}><input type="checkbox" disabled={!canAdmin} checked={permissions.includes(role.value)} onChange={() => setPermissions((current) => current.includes(role.value) ? current.filter((item) => item !== role.value) : [...current, role.value])} className="mr-1.5 accent-[var(--primary)]" />{role.label}</label>)}{permissions.length === 0 && <span className="text-xs font-semibold text-slate-500">Viewer only</span>}{canAdmin && <><button onClick={() => onSave(member, permissions)} className="ml-auto text-xs font-bold text-primary">Save roles</button><button onClick={() => onSave(member, permissions, member.status === "active" ? "inactive" : "active")} className="text-xs font-bold text-slate-500">{member.status === "active" ? "Deactivate" : "Reactivate"}</button></>}</div></div>;
}
