"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, useTransition } from "react";
import { Mail, UserPlus } from "lucide-react";
import { toast } from "sonner";
import type { OrganisationPermission } from "@/types/accesscheck";
import Pagination from "@/app/components/settings/Pagination";

const PAGE_SIZE = 10;

type Member = { id: string; email: string | null; first_name: string | null; last_name: string | null; avatar_url: string | null; job_title: string | null; status: "active" | "inactive"; last_active_at: string | null; organisation_member_permissions: Array<{ permission: OrganisationPermission }> };
const memberName = (member: Member) => [member.first_name, member.last_name].filter(Boolean).join(" ");
type Invitation = { id: string; email: string; permissions: OrganisationPermission[]; status: string; expires_at: string; created_at: string };
// "reviewer" is still a valid permission in the DB and API — it is just not
// offered in the UI, so an existing reviewer grant is preserved on save rather
// than being cleared.
const roles: Array<{ value: OrganisationPermission; label: string; description: string }> = [{ value: "admin", label: "Admin", description: "Manage organisation" }, { value: "author", label: "Author", description: "Create and edit cases" }];

export default function MembersClient({ initialMembers, initialInvitations, memberLimit }: { initialMembers: Member[]; initialInvitations: Invitation[]; memberLimit: number }) {
  const router = useRouter(); const [email, setEmail] = useState(""); const [inviteRoles, setInviteRoles] = useState<OrganisationPermission[]>(["author"]); const pending = initialInvitations.filter((invite) => invite.status === "pending");
  // A pending invitation reserves a seat, so it counts alongside active members.
  // `initialMembers` includes deactivated rows, which do not.
  const seatsUsed = initialMembers.filter((member) => member.status === "active").length + pending.length;
  const isFull = seatsUsed >= memberLimit;
  const [page, setPage] = useState(1); const [paging, startTransition] = useTransition();
  // Clamp: deactivating or inviting refreshes the list, which can shrink it under the current page.
  const pageCount = Math.max(1, Math.ceil(initialMembers.length / PAGE_SIZE));
  const currentPage = Math.min(page, pageCount);
  const visibleMembers = initialMembers.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE);
  const toggle = (values: OrganisationPermission[], value: OrganisationPermission) => values.includes(value) ? values.filter((item) => item !== value) : [...values, value];
  const updateMember = async (member: Member, permissions: OrganisationPermission[], status = member.status) => { const response = await fetch("/api/organisations/members", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ memberId: member.id, permissions, status }) }); const body = await response.json(); if (!response.ok) return toast.error(body.error); toast.success("Member updated"); router.refresh(); };
  const invite = async (targetEmail = email, permissions = inviteRoles) => { const response = await fetch("/api/organisations/invitations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: targetEmail, permissions }) }); const body = await response.json(); if (!response.ok) return toast.error(body.error); toast.success(targetEmail === email ? "Invitation sent" : "Invitation resent"); setEmail(""); router.refresh(); };
  const cancel = async (id: string) => { const response = await fetch("/api/organisations/invitations", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ invitationId: id, action: "cancel" }) }); const body = await response.json(); if (!response.ok) return toast.error(body.error); toast.success("Invitation cancelled"); router.refresh(); };
  return <div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-baseline justify-between gap-2"><h2 className="font-bold">Invite member</h2><span className={`text-xs font-bold ${isFull ? "text-amber-700" : "text-slate-500"}`}>{seatsUsed} of {memberLimit} seats used</span></div><p className="text-sm text-slate-500">{isFull ? "All seats are taken. Deactivate a member or cancel a pending invitation to free one, or contact AccessCheck to add seats." : "New members receive baseline Viewer access plus selected roles. A pending invitation reserves a seat."}</p><div className="mt-4 grid gap-3 lg:grid-cols-[1fr_1.5fr_auto]"><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="name@council.gov.uk" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /><div className="flex flex-wrap gap-2">{roles.map((role) => <label key={role.value} className={`inline-flex cursor-pointer items-center rounded-xl border px-3 py-2 text-xs font-bold leading-none ${inviteRoles.includes(role.value) ? "border-primary bg-primary-light text-primary" : "border-slate-200"}`}><input type="checkbox" className="sr-only" checked={inviteRoles.includes(role.value)} onChange={() => setInviteRoles(toggle(inviteRoles, role.value))} />{role.label}</label>)}</div><button onClick={() => invite()} disabled={!email.trim() || isFull} title={isFull ? `Seat limit of ${memberLimit} reached` : undefined} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40"><UserPlus size={17} /> Invite</button></div></section>
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-bold">Organisation members</h2><p className="text-sm text-slate-500">Viewer access is included for every active member.</p></div><div className={`divide-y divide-slate-100 transition-opacity ${paging ? "opacity-60" : ""}`}>{visibleMembers.map((member) => <MemberRow key={member.id} member={member} onSave={updateMember} seatsFull={isFull} memberLimit={memberLimit} />)}</div><div className="px-5 pb-4"><Pagination page={currentPage} pageCount={pageCount} total={initialMembers.length} pageSize={PAGE_SIZE} pending={paging} onChange={(next) => startTransition(() => setPage(next))} label="members" /></div></section>
    {pending.length > 0 && <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-bold">Pending invitations</h2></div><div className="divide-y divide-slate-100">{pending.map((invitation) => <div key={invitation.id} className="flex flex-wrap items-center gap-3 px-5 py-4"><Mail size={18} className="text-slate-400" /><div className="min-w-0 flex-1"><p className="truncate font-semibold">{invitation.email}</p><p className="text-xs text-slate-500">{invitation.permissions.join(", ") || "Viewer"} · expires {new Date(invitation.expires_at).toLocaleDateString("en-GB")}</p></div><button onClick={() => invite(invitation.email, invitation.permissions)} className="text-xs font-bold text-primary">Resend</button><button onClick={() => cancel(invitation.id)} className="text-xs font-bold text-red-600">Cancel</button></div>)}</div></section>}
  </div>;
}

function MemberRow({ member, onSave, seatsFull, memberLimit }: { member: Member; onSave: (member: Member, permissions: OrganisationPermission[], status?: "active" | "inactive") => void; seatsFull: boolean; memberLimit: number }) {
  const [permissions, setPermissions] = useState(member.organisation_member_permissions.map((role) => role.permission));
  const name = memberName(member);
  return <div className="px-5 py-4"><div className="flex flex-wrap items-start gap-4">{member.avatar_url
    // eslint-disable-next-line @next/next/no-img-element -- user-supplied storage URL, no loader config
    ? <img src={member.avatar_url} alt="" className="h-10 w-10 shrink-0 rounded-xl object-cover" />
    : <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary-light font-extrabold text-primary">{(name || member.email || "U")[0].toUpperCase()}</div>}<div className="min-w-0 flex-1"><Link href={`/settings/members/${member.id}`} className="font-bold text-slate-900 hover:text-primary hover:underline">{name || member.email || "Unnamed member"}</Link><p className="text-xs text-slate-500">{member.email}{member.job_title ? ` · ${member.job_title}` : ""}</p></div><span className={`rounded-lg px-2.5 py-1 text-xs font-bold capitalize ${member.status === "active" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{member.status}</span></div><div className="mt-3 flex flex-wrap items-center gap-2 pl-14">{roles.map((role) => <label key={role.value} title={role.description} className={`inline-flex cursor-pointer items-center rounded-lg border px-2.5 py-1.5 text-xs font-bold leading-none ${permissions.includes(role.value) ? "border-primary/30 bg-primary-light text-primary" : "border-slate-200 text-slate-500"}`}><input type="checkbox" checked={permissions.includes(role.value)} onChange={() => setPermissions((current) => current.includes(role.value) ? current.filter((item) => item !== role.value) : [...current, role.value])} className="mr-1.5 accent-[var(--primary)]" />{role.label}</label>)}{permissions.length === 0 && <span className="text-xs font-semibold text-slate-500">Viewer only</span>}<button onClick={() => onSave(member, permissions)} className="ml-auto text-xs font-bold text-primary">Save roles</button><button onClick={() => onSave(member, permissions, member.status === "active" ? "inactive" : "active")} disabled={member.status !== "active" && seatsFull} title={member.status !== "active" && seatsFull ? `Seat limit of ${memberLimit} reached` : undefined} className="text-xs font-bold text-slate-500 disabled:opacity-40">{member.status === "active" ? "Deactivate" : "Reactivate"}</button></div></div>;
}
