"use client";

import { useEffect, useRef } from "react";
import { usePathname, useSearchParams } from "next/navigation";
import { usePostHog } from "posthog-js/react";
import { track } from "@vercel/analytics";

/**
 * Engagement-depth instrumentation — the part that answers "was that a person?"
 *
 * Why this exists: a mail-security gateway (Defender Safe Links, Mimecast,
 * Proofpoint) fetches every URL in an email to check it. Most only issue an
 * HTTP request, which is why Loops reports clicks that no human made. The more
 * aggressive ones "detonate" the link in a headless browser, which DOES run
 * JavaScript and WILL fire a pageview — so a pageview alone is better evidence
 * than a click, but it is still not proof.
 *
 * What a sandbox does not do is read. It loads the page for a few seconds, does
 * not scroll, does not move a pointer, and leaves. So we record three things a
 * detonation sandbox essentially never produces, and treat any two of them
 * together as a verified human.
 *
 * Every listener is passive and self-removing; nothing here blocks paint.
 */

const DWELL_MS = 30_000;
const SCROLL_THRESHOLD = 0.5;
const SIGNALS_FOR_HUMAN = 2;

export function HumanSignals() {
  const posthog = usePostHog();
  const pathname = usePathname();
  const searchParams = useSearchParams();

  const fired = useRef<Set<string>>(new Set());
  const verified = useRef(false);

  useEffect(() => {
    // Reset per page so each route is judged on its own merits.
    fired.current = new Set();
    verified.current = false;

    const fromEmail = searchParams?.get("utm_source") === "loops";
    const emailId = searchParams?.get("utm_content") ?? null;

    const base = {
      from_email: fromEmail,
      email_id: emailId,
      utm_campaign: searchParams?.get("utm_campaign") ?? null,
      path: pathname,
    };

    const emit = (name: string, extra: Record<string, unknown> = {}) => {
      if (fired.current.has(name)) return;
      fired.current.add(name);

      const props = { ...base, ...extra };
      posthog?.capture(name, props);

      // Vercel custom events require a Pro plan; on Hobby this is a no-op
      // rather than an error, so it is safe to call unconditionally.
      try {
        track(name, props as Record<string, string | number | boolean | null>);
      } catch {
        /* analytics must never break the page */
      }

      if (!verified.current && fired.current.size >= SIGNALS_FOR_HUMAN) {
        verified.current = true;
        const summary = { ...base, signals: [...fired.current].join(",") };
        posthog?.capture("verified_human", summary);
        try {
          track("verified_human", summary as Record<string, string | number | boolean | null>);
        } catch {
          /* no-op */
        }
      }
    };

    // ---- Signal 1: real scrolling -------------------------------------
    const onScroll = () => {
      const doc = document.documentElement;
      const scrollable = doc.scrollHeight - window.innerHeight;
      if (scrollable <= 0) return;
      const depth = window.scrollY / scrollable;
      if (depth >= SCROLL_THRESHOLD) {
        emit("human_scroll", { depth: Math.round(depth * 100) });
        window.removeEventListener("scroll", onScroll);
      }
    };
    window.addEventListener("scroll", onScroll, { passive: true });

    // ---- Signal 2: foreground dwell time -------------------------------
    // Counts only time the tab is actually visible, so a backgrounded tab
    // left open all afternoon does not qualify as attention.
    let visibleMs = 0;
    let lastTick = document.visibilityState === "visible" ? Date.now() : null;

    const accumulate = () => {
      if (lastTick !== null) {
        visibleMs += Date.now() - lastTick;
        lastTick = null;
      }
    };
    const onVisibility = () => {
      if (document.visibilityState === "visible") {
        lastTick = Date.now();
      } else {
        accumulate();
      }
    };
    document.addEventListener("visibilitychange", onVisibility);

    const dwellTimer = window.setInterval(() => {
      const now = lastTick !== null ? visibleMs + (Date.now() - lastTick) : visibleMs;
      if (now >= DWELL_MS) {
        emit("human_dwell", { seconds: Math.round(now / 1000) });
        window.clearInterval(dwellTimer);
      }
    }, 2_000);

    // ---- Signal 3: a trusted, physical interaction ---------------------
    // event.isTrusted is false for anything dispatched by script, which rules
    // out synthetic interaction generated by a crawler.
    const onInteract = (e: Event) => {
      if (!e.isTrusted) return;
      emit("human_interact", { kind: e.type });
      cleanupInteract();
    };
    const interactEvents = ["pointerdown", "keydown", "wheel", "touchstart"] as const;
    const cleanupInteract = () => {
      interactEvents.forEach((t) => window.removeEventListener(t, onInteract));
    };
    interactEvents.forEach((t) =>
      window.addEventListener(t, onInteract, { passive: true, once: false }),
    );

    return () => {
      window.removeEventListener("scroll", onScroll);
      document.removeEventListener("visibilitychange", onVisibility);
      window.clearInterval(dwellTimer);
      cleanupInteract();
    };
  }, [pathname, searchParams, posthog]);

  return null;
}
