
  create table "public"."survey_evidences" (
    "id" uuid not null default gen_random_uuid(),
    "survey_id" bigint,
    "created_at" timestamp with time zone default now(),
    "file_name" text,
    "file_type" text,
    "mime_type" text not null,
    "file_url" text not null,
    "section" text,
    "field_reference" text,
    "caption" text
      );


alter table "public"."survey_evidences" enable row level security;


  create table "public"."surveys" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "status" text,
    "thumbnail_url" text,
    "uprn" text,
    "door_number" text,
    "street_number" text,
    "building_name" text,
    "street" text,
    "postcode" text,
    "inspector_name" text,
    "inspector_phone" text,
    "inspection_date" date,
    "is_multiple_properties" boolean default false,
    "property_type" text,
    "tenure_type" text,
    "housing_association_name" text,
    "entrance_level" text,
    "entrance_floor_level" smallint,
    "num_bedrooms" smallint,
    "num_bed_spaces" smallint,
    "num_lifts_dwelling" smallint default 0,
    "has_through_floor_lift" boolean,
    "through_floor_lift_dim_width" numeric(5,1),
    "through_floor_lift_dim_depth" numeric(5,1),
    "has_ceiling_track_hoist" boolean,
    "has_step_lift" boolean,
    "has_stair_lift" boolean,
    "has_platform_stair_lift" boolean,
    "has_level_access_shower" boolean,
    "stop_flag_no_lift_or_ramp" boolean default false,
    "has_communal_front_door" boolean,
    "communal_door_steps_count" smallint,
    "communal_door_threshold_height" text,
    "communal_door_opening_width" numeric(5,1),
    "has_communal_ramp" boolean,
    "communal_ramp_adequate_platform" boolean,
    "communal_ramp_ah" numeric(5,1),
    "communal_ramp_al" numeric(5,1),
    "communal_ramp_bh" numeric(5,1),
    "communal_ramp_bl" numeric(5,1),
    "has_communal_lift" boolean,
    "communal_lift_dim_width" numeric(5,1),
    "communal_lift_dim_depth" numeric(5,1),
    "communal_lift_door_width" numeric(5,1),
    "communal_lift_id" text,
    "communal_lift_count_in_block" smallint,
    "property_door_steps_count" smallint,
    "property_door_threshold_height" text,
    "property_door_opening_width" numeric(5,1),
    "stop_flag_too_many_steps" boolean default false,
    "has_property_ramp" boolean,
    "property_ramp_adequate_platform" boolean,
    "property_ramp_ah" numeric(5,1),
    "property_ramp_al" numeric(5,1),
    "property_ramp_bh" numeric(5,1),
    "property_ramp_bl" numeric(5,1),
    "access_bed1" boolean,
    "access_bed2" boolean,
    "access_bathroom_no_toilet" boolean,
    "access_combined_bath_toilet" boolean,
    "access_separate_toilet" boolean,
    "access_living_room" boolean,
    "access_kitchen" boolean,
    "access_other" boolean,
    "above_bed1" boolean,
    "above_bed2" boolean,
    "above_bathroom_no_toilet" boolean,
    "above_combined_bath_toilet" boolean,
    "above_separate_toilet" boolean,
    "above_living_room" boolean,
    "above_kitchen" boolean,
    "above_other" boolean,
    "below_bed1" boolean,
    "below_bed2" boolean,
    "below_bathroom_no_toilet" boolean,
    "below_combined_bath_toilet" boolean,
    "below_separate_toilet" boolean,
    "below_living_room" boolean,
    "below_kitchen" boolean,
    "below_other" boolean,
    "internal_steps_count" smallint,
    "stop_flag_internal_steps" boolean default false,
    "has_internal_stairs" boolean,
    "stair_width_cm" numeric(5,1),
    "has_straight_stairs" boolean,
    "has_curved_stairs" boolean,
    "stair_70cm_clearance" boolean,
    "stop_flag_stair_width" boolean default false,
    "stop_flag_no_clearance_no_exit" boolean default false,
    "has_second_exit" boolean,
    "second_exit_to_street" boolean,
    "second_exit_steps_count" smallint,
    "second_exit_threshold_height" text,
    "second_exit_door_width" numeric(5,1),
    "has_ramped_second_exit" boolean,
    "second_exit_ramp_platform" boolean,
    "second_exit_ramp_ah" numeric(5,1),
    "second_exit_ramp_al" numeric(5,1),
    "second_exit_ramp_bh" numeric(5,1),
    "second_exit_ramp_bl" numeric(5,1),
    "has_private_garden" boolean,
    "has_balcony" boolean,
    "garden_steps_count" smallint,
    "balcony_steps_count" smallint,
    "hallway_width_head_on_cm" numeric(5,1),
    "hallway_width_turn_cm" numeric(5,1),
    "has_wheelchair_storage" boolean,
    "wheelchair_storage_dim_width" numeric(5,1),
    "wheelchair_storage_dim_depth" numeric(5,1),
    "wheelchair_charging_socket" boolean,
    "kitchen_turning_150x150" boolean,
    "kitchen_turning_170x140" boolean,
    "kitchen_wheelchair_accessible" boolean,
    "kitchen_separate_from_living" boolean,
    "has_separate_toilet" boolean,
    "toilet_dim_width" numeric(5,1),
    "toilet_dim_depth" numeric(5,1),
    "toilet_count" smallint,
    "toilet_lateral_space_cm" numeric(5,1),
    "bathroom_turning_150x150" boolean,
    "bathroom_dim_width" numeric(5,1),
    "bathroom_dim_depth" numeric(5,1),
    "bathroom_has_level_access_shower" boolean,
    "bathroom_has_bath" boolean,
    "bathroom_has_la_shower_and_bath" boolean,
    "bathroom_next_to_toilet" boolean,
    "bathroom_toilet_lateral_space" numeric(5,1),
    "door_width_living_room" numeric(5,1),
    "door_width_kitchen" numeric(5,1),
    "door_width_bed1" numeric(5,1),
    "door_width_bed2" numeric(5,1),
    "door_width_bed3" numeric(5,1),
    "door_width_bathroom" numeric(5,1),
    "door_width_separate_toilet" numeric(5,1),
    "door_width_balcony" numeric(5,1),
    "has_carport_next_to_property" boolean,
    "has_covered_carport_or_garage" boolean,
    "has_designated_parking_bay" boolean,
    "shops_within_100m" boolean,
    "transport_within_100m" boolean,
    "transport_dlr" boolean,
    "transport_bus" boolean,
    "transport_train" boolean,
    "transport_tube" boolean,
    "can_be_adapted" boolean,
    "comments" text,
    "user_id" uuid not null
      );


alter table "public"."surveys" enable row level security;

CREATE UNIQUE INDEX survey_evidences_pkey ON public.survey_evidences USING btree (id);

CREATE UNIQUE INDEX surveys_pkey ON public.surveys USING btree (id);

alter table "public"."survey_evidences" add constraint "survey_evidences_pkey" PRIMARY KEY using index "survey_evidences_pkey";

alter table "public"."surveys" add constraint "surveys_pkey" PRIMARY KEY using index "surveys_pkey";

alter table "public"."survey_evidences" add constraint "survey_evidences_survey_id_fkey" FOREIGN KEY (survey_id) REFERENCES public.surveys(id) ON DELETE CASCADE not valid;

alter table "public"."survey_evidences" validate constraint "survey_evidences_survey_id_fkey";

alter table "public"."surveys" add constraint "surveys_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."surveys" validate constraint "surveys_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.update_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$function$
;

grant delete on table "public"."survey_evidences" to "anon";

grant insert on table "public"."survey_evidences" to "anon";

grant references on table "public"."survey_evidences" to "anon";

grant select on table "public"."survey_evidences" to "anon";

grant trigger on table "public"."survey_evidences" to "anon";

grant truncate on table "public"."survey_evidences" to "anon";

grant update on table "public"."survey_evidences" to "anon";

grant delete on table "public"."survey_evidences" to "authenticated";

grant insert on table "public"."survey_evidences" to "authenticated";

grant references on table "public"."survey_evidences" to "authenticated";

grant select on table "public"."survey_evidences" to "authenticated";

grant trigger on table "public"."survey_evidences" to "authenticated";

grant truncate on table "public"."survey_evidences" to "authenticated";

grant update on table "public"."survey_evidences" to "authenticated";

grant delete on table "public"."survey_evidences" to "postgres";

grant insert on table "public"."survey_evidences" to "postgres";

grant references on table "public"."survey_evidences" to "postgres";

grant select on table "public"."survey_evidences" to "postgres";

grant trigger on table "public"."survey_evidences" to "postgres";

grant truncate on table "public"."survey_evidences" to "postgres";

grant update on table "public"."survey_evidences" to "postgres";

grant delete on table "public"."survey_evidences" to "service_role";

grant insert on table "public"."survey_evidences" to "service_role";

grant references on table "public"."survey_evidences" to "service_role";

grant select on table "public"."survey_evidences" to "service_role";

grant trigger on table "public"."survey_evidences" to "service_role";

grant truncate on table "public"."survey_evidences" to "service_role";

grant update on table "public"."survey_evidences" to "service_role";

grant delete on table "public"."surveys" to "anon";

grant insert on table "public"."surveys" to "anon";

grant references on table "public"."surveys" to "anon";

grant select on table "public"."surveys" to "anon";

grant trigger on table "public"."surveys" to "anon";

grant truncate on table "public"."surveys" to "anon";

grant update on table "public"."surveys" to "anon";

grant delete on table "public"."surveys" to "authenticated";

grant insert on table "public"."surveys" to "authenticated";

grant references on table "public"."surveys" to "authenticated";

grant select on table "public"."surveys" to "authenticated";

grant trigger on table "public"."surveys" to "authenticated";

grant truncate on table "public"."surveys" to "authenticated";

grant update on table "public"."surveys" to "authenticated";

grant delete on table "public"."surveys" to "postgres";

grant insert on table "public"."surveys" to "postgres";

grant references on table "public"."surveys" to "postgres";

grant select on table "public"."surveys" to "postgres";

grant trigger on table "public"."surveys" to "postgres";

grant truncate on table "public"."surveys" to "postgres";

grant update on table "public"."surveys" to "postgres";

grant delete on table "public"."surveys" to "service_role";

grant insert on table "public"."surveys" to "service_role";

grant references on table "public"."surveys" to "service_role";

grant select on table "public"."surveys" to "service_role";

grant trigger on table "public"."surveys" to "service_role";

grant truncate on table "public"."surveys" to "service_role";

grant update on table "public"."surveys" to "service_role";


  create policy "Enable delete for all users"
  on "public"."survey_evidences"
  as permissive
  for delete
  to public
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."survey_evidences"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Enable read access for all users"
  on "public"."survey_evidences"
  as permissive
  for select
  to public
using (true);



  create policy "Enable delete for users based on user_id"
  on "public"."surveys"
  as permissive
  for delete
  to public
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable insert for users based on user_id"
  on "public"."surveys"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for all users"
  on "public"."surveys"
  as permissive
  for select
  to public
using (true);



  create policy "Policy with table joins"
  on "public"."surveys"
  as permissive
  for update
  to public
using (true);


CREATE TRIGGER trg_surveys_updated_at BEFORE UPDATE ON public.surveys FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

drop trigger if exists "protect_buckets_delete" on "storage"."buckets";

drop trigger if exists "protect_objects_delete" on "storage"."objects";


  create policy "Authenticated users can upload evidence files"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'evidences'::text));



  create policy "Public can view evidence files"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'evidences'::text));




