ALTER TABLE surveys
ADD COLUMN IF NOT EXISTS raw_ai_data JSONB,
ADD COLUMN IF NOT EXISTS overall_grade TEXT,
ADD COLUMN IF NOT EXISTS compliance_score NUMERIC,
ADD COLUMN IF NOT EXISTS ai_confidence NUMERIC;
